version: '3.4'

services:
  
  customerservice:
    build:
      context: .
      dockerfile: CustomerService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5002:80
    image: customerservice
    container_name: customerservice
    
  orderservice:
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5001:80
    image: orderservice
    container_name: orderservice

  