version: '3.4'

services:
  orderservice:
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5001:80
    image: orderservice
    container_name: orderservice
  userservice:
    build:
      context: .
      dockerfile: UserService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5002:80
    image: userservice
    container_name: userservice
    