version: '3.4'

networks:

  backend_network:
    driver: bridge

services:

  customerservice:
    build:
      context: .
      dockerfile: CustomerService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    ports:
      - 5001:80
    image: customerservice
    container_name: customerservice
    networks:
      - backend_network

  orderservice:
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    ports:
      - 5002:80
    image: orderservice
    container_name: orderservice
    networks:
      - backend_network

  apigateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    ports:
      - 5003:80
    image: apigateway
    container_name: apigateway
    networks:
      - backend_network